# Generated by Django 3.2 on 2021-06-12 02:23

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('messagge', models.TextField(verbose_name='mensaje')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=70, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('about_title', models.CharField(max_length=70, verbose_name='titulo sobre nosotros')),
                ('about_text', models.TextField(verbose_name='contenido sobre nosotros')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo')),
                ('phone', models.CharField(max_length=20, verbose_name='celular')),
            ],
            options={
                'verbose_name': 'página principal',
                'verbose_name_plural': 'páginas principales',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
            ],
            options={
                'verbose_name': 'suscriptor',
                'verbose_name_plural': 'suscriptores',
            },
        ),
    ]
