# Generated by Django 3.2 on 2021-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_messagge_contact_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'homepage', 'verbose_name_plural': 'main pages'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
        migrations.AddField(
            model_name='home',
            name='body_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email body'),
        ),
        migrations.AddField(
            model_name='home',
            name='repository',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='repository'),
        ),
        migrations.AddField(
            model_name='home',
            name='subject_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='email subject'),
        ),
        migrations.AddField(
            model_name='home',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='web'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about_text',
            field=models.TextField(verbose_name='about description'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about_title',
            field=models.CharField(max_length=70, verbose_name='about title'),
        ),
        migrations.AlterField(
            model_name='home',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='home',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=70, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
