# Generated by Django 3.2 on 2021-06-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='usuario')),
                ('names', models.CharField(blank=True, max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='apellidos')),
                ('occupation', models.CharField(blank=True, max_length=50, verbose_name='ocupación')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[['H', 'Hombre'], ['M', 'Mujer'], ['N', 'No binario'], ['O', 'Otro'], ['P', 'Prefiero no decir']], max_length=1, verbose_name='Genero')),
                ('confirm_code', models.CharField(blank=True, max_length=6, verbose_name='código de confirmación')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿es staff?')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿es activo?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
