# Generated by Django 3.2 on 2021-07-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210630_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[['M', 'Hombre'], ['W', 'Mujer'], ['N', 'No binario']], max_length=1, verbose_name='gender'),
        ),
    ]
